# Generated by Django 4.2.4 on 2023-08-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("organico", "Orgânico"),
                            ("nao organico", "Não Orgânico"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        default="media/img_feiras/default.jpg", upload_to="img_feiras"
                    ),
                ),
                ("rua", models.CharField(max_length=25)),
                ("complemento", models.CharField(max_length=25)),
                ("bairro", models.CharField(max_length=15)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("df", "Distrito Federal"),
                            ("go", "Goiás"),
                            ("mg", "Minas Gerais"),
                        ],
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
